// Code generated by protoc-gen-go. DO NOT EDIT.
// source: appending.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Command int32

const (
	Command_Get Command = 0
	Command_Set Command = 1
)

var Command_name = map[int32]string{
	0: "Get",
	1: "Set",
}

var Command_value = map[string]int32{
	"Get": 0,
	"Set": 1,
}

func (x Command) String() string {
	return proto.EnumName(Command_name, int32(x))
}

func (Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34d27f26b2186c28, []int{0}
}

type AppendRequest struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Leader               int64    `protobuf:"varint,2,opt,name=leader,proto3" json:"leader,omitempty"`
	LastLogIndex         int64    `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm          int64    `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	Entries              []*Entry `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIndex    int64    `protobuf:"varint,6,opt,name=leaderCommitIndex,proto3" json:"leaderCommitIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRequest) Reset()         { *m = AppendRequest{} }
func (m *AppendRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()    {}
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d27f26b2186c28, []int{0}
}

func (m *AppendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRequest.Unmarshal(m, b)
}
func (m *AppendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRequest.Marshal(b, m, deterministic)
}
func (m *AppendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRequest.Merge(m, src)
}
func (m *AppendRequest) XXX_Size() int {
	return xxx_messageInfo_AppendRequest.Size(m)
}
func (m *AppendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRequest proto.InternalMessageInfo

func (m *AppendRequest) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendRequest) GetLeader() int64 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *AppendRequest) GetLastLogIndex() int64 {
	if m != nil {
		return m.LastLogIndex
	}
	return 0
}

func (m *AppendRequest) GetLastLogTerm() int64 {
	if m != nil {
		return m.LastLogTerm
	}
	return 0
}

func (m *AppendRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *AppendRequest) GetLeaderCommitIndex() int64 {
	if m != nil {
		return m.LeaderCommitIndex
	}
	return 0
}

type AppendResponse struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendResponse) Reset()         { *m = AppendResponse{} }
func (m *AppendResponse) String() string { return proto.CompactTextString(m) }
func (*AppendResponse) ProtoMessage()    {}
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d27f26b2186c28, []int{1}
}

func (m *AppendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResponse.Unmarshal(m, b)
}
func (m *AppendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResponse.Marshal(b, m, deterministic)
}
func (m *AppendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResponse.Merge(m, src)
}
func (m *AppendResponse) XXX_Size() int {
	return xxx_messageInfo_AppendResponse.Size(m)
}
func (m *AppendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResponse proto.InternalMessageInfo

func (m *AppendResponse) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *AppendResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Entry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Command              Command  `protobuf:"varint,3,opt,name=Command,proto3,enum=api.Command" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_34d27f26b2186c28, []int{2}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Entry) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Entry) GetCommand() Command {
	if m != nil {
		return m.Command
	}
	return Command_Get
}

func init() {
	proto.RegisterEnum("api.Command", Command_name, Command_value)
	proto.RegisterType((*AppendRequest)(nil), "api.AppendRequest")
	proto.RegisterType((*AppendResponse)(nil), "api.AppendResponse")
	proto.RegisterType((*Entry)(nil), "api.Entry")
}

func init() {
	proto.RegisterFile("appending.proto", fileDescriptor_34d27f26b2186c28)
}

var fileDescriptor_34d27f26b2186c28 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0x9a, 0x36, 0xd1, 0x69, 0x6d, 0xeb, 0x28, 0x12, 0xf4, 0x52, 0x82, 0x48, 0x11, 0xc9,
	0xa1, 0x3d, 0x0a, 0x82, 0x4a, 0x15, 0xd1, 0xd3, 0x2a, 0x0a, 0xde, 0xd2, 0x66, 0x28, 0x81, 0x76,
	0xb3, 0x66, 0xb7, 0x60, 0x7f, 0xa8, 0xff, 0xc7, 0x64, 0xb6, 0x11, 0x83, 0xde, 0xde, 0xc7, 0xee,
	0xbc, 0x7d, 0x3b, 0xd0, 0x8f, 0x95, 0x22, 0x99, 0xa4, 0x72, 0x11, 0xa9, 0x3c, 0x33, 0x19, 0xba,
	0xb1, 0x4a, 0xc3, 0x2f, 0x07, 0xf6, 0xae, 0xd9, 0x10, 0xf4, 0xb1, 0x26, 0x6d, 0x10, 0xa1, 0x65,
	0x28, 0x5f, 0x05, 0xce, 0xd0, 0x19, 0xb9, 0x82, 0x31, 0x1e, 0x81, 0xb7, 0xa4, 0x38, 0xa1, 0x3c,
	0x68, 0xb2, 0xba, 0x65, 0x18, 0x42, 0x77, 0x19, 0x6b, 0xf3, 0x94, 0x2d, 0x1e, 0x64, 0x42, 0x9f,
	0x81, 0xcb, 0x6e, 0x4d, 0xc3, 0x21, 0x74, 0xb6, 0xfc, 0xa5, 0x1c, 0xdb, 0xe2, 0x23, 0xbf, 0x25,
	0x3c, 0x05, 0x9f, 0xa4, 0xc9, 0x53, 0xd2, 0x41, 0x7b, 0xe8, 0x8e, 0x3a, 0x63, 0x88, 0x8a, 0xa7,
	0x45, 0xd3, 0x42, 0xdb, 0x88, 0xca, 0xc2, 0x0b, 0xd8, 0xb7, 0xa9, 0xb7, 0xd9, 0x6a, 0x95, 0x1a,
	0x1b, 0xe8, 0xf1, 0xb4, 0xbf, 0x46, 0x78, 0x05, 0xbd, 0xaa, 0x96, 0x56, 0x99, 0xd4, 0xf4, 0x6f,
	0xaf, 0x00, 0x7c, 0xbd, 0x9e, 0xcf, 0x49, 0x6b, 0x2e, 0xb6, 0x23, 0x2a, 0x1a, 0xbe, 0x41, 0x9b,
	0xf3, 0x71, 0x00, 0xee, 0x23, 0x6d, 0xf8, 0xd6, 0xae, 0x28, 0x21, 0x1e, 0x42, 0xfb, 0x35, 0x5e,
	0xae, 0x89, 0xaf, 0x34, 0x85, 0x25, 0x78, 0x06, 0x7e, 0x99, 0x1f, 0xcb, 0x84, 0x7f, 0xa1, 0x37,
	0xee, 0x72, 0x89, 0xad, 0x26, 0x2a, 0xf3, 0xfc, 0xe4, 0xe7, 0x1c, 0xfa, 0xe0, 0xde, 0x93, 0x19,
	0x34, 0x4a, 0xf0, 0x5c, 0x00, 0x67, 0x7c, 0x07, 0xfd, 0xa9, 0xad, 0x6b, 0x1f, 0x5f, 0x7c, 0xf1,
	0x04, 0x3c, 0x8b, 0x11, 0x79, 0x60, 0x6d, 0x59, 0xc7, 0x07, 0x35, 0xcd, 0x36, 0x0d, 0x1b, 0x37,
	0xde, 0x7b, 0x2b, 0xba, 0x54, 0xb3, 0x99, 0xc7, 0x9b, 0x9e, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xdf, 0x36, 0x5e, 0x22, 0xfc, 0x01, 0x00, 0x00,
}
